version: "3.8"
services:
  veg-app:
    build: .
    image: veg-app:v1
    container_name: veg-order-container
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI: 'mongodb://mongodb:27017/vegetable_order_app'
    
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
